version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: eingress-api:latest  # Custom image name
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
