name: Build and push Docker image to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: jairoeingressregistry.azurecr.io
        username: EINGRESS-ADMIN
        password: ${{ secrets.JAIROEINGRESSREGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: jairoeingressregistry.azurecr.io/eingressapi:cd